# Site settings
title: Freelancer
detail: รับทำโปรเจคจบ php jsp vb c sharp อื่นๆ ราคาตามตกลง
email: projectdeks@gmail.com
url: http://projectdeks.com/
description: "รับทำโปรเจคจบ php jsp vb c sharp อื่นๆ ราคาตามตกลง"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Projectdek
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
   - title: facebook
     url: https://www.facebook.com/pjdek
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: -
  - line: -

# Credits content
credits: '...'

# Build settings
markdown: kramdown
permalink: pretty
